export const callInterval = 3600000
export const constants = {
  DAUCode: 41001,
  WAUCode: 41002,
  MAUCode: 41003,
  DNUCode: 41009,
  DASTCode: 41010,
  WASTCode: 41011,
  MASTCode: 41012,
  RETENTION_CATEGORY: 40001,
  EVENT_CATEGORY: 10001,
  EVENT_DEV_CATEGORY: 20001,
  FAILED_RETENTION: 'failed_retention',
  UID: 'uid',
  PREVIOUS_RETENTION_META: 'previous_retention_meta',
  GEO: 'geo',
  MOBILE_PLATFORM_CODE: 16,
  WEB_PLATFORM_CODE: 70,
  GEO_IP_PATH: 'Geo_Ip_Path',
  EVENT_PATH: 'Event_Path',
  EVENT_RETENTION_PATH: 'Event_Retention_Path',
  EVENT_PUSH_INTERVAL: 'Event_Push_Interval',
  DEFAULT_EVENT_PUSH_INTERVAL: 1,
  SESSION_ID: 'sessionId',
  RETRY_INTERVAL: 'Retry_Interval',
  DEFAULT_RETRY_INTERVAL: 1,
  MANIFEST_REFRESH_INTERVAL: 'Manifest_Refresh_Interval',
  API_ENDPOINT: 'Api_Endpoint',
  ROOT_KEY: 'Root',
  PRODUCTION_MODE: 'ProductionMode',
  STAGE_MODE: 'StageMode',
  IS_NEW_USER: 'isNewUser',
  DNU: 'dnu',
  DOMAINS: 'domains',
  SDK_TOKEN: 'sdkToken',
  BOUNCE: 'bounce',
  SESSION: 'session',
  MAILER: 'mailer',
  NAVIGATION: 'navigation',
  LICENSE_EXPIRE_DAY_ALIVE: 'License_Expire_Day_Alive',
  DEFAULT_LICENSE_EXPIRE_DAY_ALIVE: 30,
  EVENT_GEOLOCATION_GRAIN: 'Event_Geolocation_Grain',
  DEFAULT_EVENT_GEOLOCATION_GRAIN: 2,
  EVENT_DEVICEINFO_GRAIN: 'Event_Deviceinfo_Grain',
  DEFAULT_EVENT_DEVICEINFO_GRAIN: 1,
  EVENT_CODIFIED_MERGECOUNTER: 'Event_Codified_Mergecounter',
  DEFAULT_EVENT_CODIFIED_MERGECOUNTER: 1,
  EVENT_SYSTEM_MERGECOUNTER: 'Event_System_Mergecounter',
  DEFAULT_EVENT_SYSTEM_MERGECOUNTER: '1',
  EVENT_PUSH_EVENTSCOUNTER: 'Event_Push_Eventscounter',
  DEFAULT_EVENT_PUSH_EVENTSCOUNTER: '15',
  STORE_EVENTS_INTERVAL: 'Store_Events_Interval',
  DEFAULT_STORE_EVENTS_INTERVAL: 1,
  DOM_SUB_TREE_MODIFIED_INTERVAL: 1800000,
  SYSTEM_EVENT: 'system',
  DEV_EVENT: 'dev',
  SCROLL_EVENT: 'scroll',
  COLLECT_TIMEOUT: 5000,
  PHI_PUBLIC_KEY: 'PHI_Public_Key',
  PII_PUBLIC_KEY: 'PII_Public_Key',
  MODE_DEPLOYMENT: 'Mode_Deployment',
  PRIVACY_MODE: '0',
  FIRSTPARTY_MODE: '1',
  SESSION_START_TIME: 'session_start_time',
  SESSION_INFO: 'Session Info',
  CUSTOM_EVENT_STORAGE: 'EventsSubCode',
  DEVELOPER_EVENT_CUSTOM: 21100,
  MAP_ID_EVENT: 'map_id',
  MAP_ID_EVENT_CODE: 21001,
  PUSH_SYSTEM_EVENTS: 'SDK_Push_System_Events',
  DEFAULT_PUSH_SYSTEM_EVENTS: false,
}
export const manifestConst = {
  Geo_Ip_Path: 'v1/geo/city',
  Event_Path: 'v1/events/publish',
  Event_Retention_Path: 'v1/events/retention/publish',
  MANIFEST_PATH: 'v1/manifest/pull',
}
export const systemEventCode = {
  cut: 11101,
  copy: 11102,
  paste: 11103,
  dragstart: 11104,
  dragend: 11105,
  unload: 11106,
  load: 11107,
  error: 11108,
  abort: 11109,
  help: 11110,
  search: 11111,
  DOMActivate: 11112,
  blur: 11113,
  focus: 11114,
  DOMSubtreeModified: 11115,
  reset: 11116,
  submit: 11117,
  keypress: 11118,
  click: 11119,
  dblclick: 11120,
  contextmenu: 11121,
  offline: 11122,
  online: 11123,
  afterprint: 11124,
  touchend: 11125,
  hashchange: 11126,
  resize: 11127,
  referrer: 11501,
  dnt: 11502,
  bounce: 11504,
  navigation: 11505,
  mailer: 11506,
  session: 11507,
  hover: 11508,
  hoverc: 11509,
  scroll: 11129,
  sessionInfo: 11024,
  sdk_start: 11130,
}
export const isDevMode = process.env.NODE_ENV === 'development'
export const isHighFreqEventOff = true
export const highFreqEvents = [
  'DOMActivate',
  'DOMSubtreeModified',
  'focus',
  'blur',
  'keypress',
  'hoverc',
  'touchend',
]
export const dataEncryptionEnabled = true
