name: Vercel - Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deloy:
    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: |
            packages/sdk-browser/node_modules
            packages/sdk-core/node_modules
            packages/sdk-personal/node_modules
          key: ${{ hashFiles('packages/sdk-browser/package-lock.json') }}-${{ hashFiles('packages/sdk-core/package-lock.json') }}-${{ hashFiles('packages/sdk-personal/package-lock.json') }}

      - name: Bootstrap lerna
        run: npm run bootstrap

      - name: Build
        run: cd packages/sdk-browser && npm run build:web

      - name: Deploy to Staging
        id: deploy-staging
        if: github.event_name == 'pull_request'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: false
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: packages/sdk-browser

      - name: Comment
        if: github.event_name == 'pull_request'
        uses: NejcZdovc/comment-pr@v1
        with:
          file: 'comment_demo.md'
          identifier: 'GITHUB_ACTION_COMMENT_DEMO'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          URL: ${{steps.deploy-staging.outputs.preview-url}}

      - name: Deploy to Production
        if: github.event_name == 'push'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: false
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: '--prod'
          working-directory: packages/sdk-browser
