name: Netlify - Production

on:
  push:
    branches: [ main ]

jobs:
  deloy:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Checkout PR
      uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com
        scope: blotoutio

    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/Cypress
          node_modules
        key: ${{ runner.os }}-node12-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{secrets.TOKEN_REPO}}

    - name: Build
      run: npm run demo

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './demo'
        production-deploy: true
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: main-${{ github.event.after }}
        enable-pull-request-comment: false
        enable-commit-comment: false
        alias: main-${{ github.event.after }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1
