name: Linter

on:
  pull_request:
    branches: [main]

jobs:
  linter:
    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            packages/sdk-core/node_modules
            packages/sdk-personal/node_modules
          key: 15.x-${{ hashFiles('package-lock.json') }}-${{ hashFiles('packages/sdk-core/package-lock.json') }}-${{ hashFiles('packages/sdk-personal/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Bootstrap lerna
        run: npm run bootstrap

      - name: Run linter
        run: npm run lint
