name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release (example: 0.3.0)'
        required: true

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest
        uses: actions/checkout@v2
        with:
            token: ${{ secrets.GH_ACTION_PUSH }}

      - name: Configure git
        run: |
          git config user.email "bot@github.com"
          git config user.name "github-actions"

      - name: Version bump
        run: npx lerna version ${{ github.event.inputs.version }} -m "Version bump ${{ github.event.inputs.version }}" --yes

  create-release:
    runs-on: ubuntu-latest
    needs: [version-bump]
    timeout-minutes: 1

    steps:
      - name: Checkout the latest
        uses: actions/checkout@v2

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: true
          prerelease: false

  publish:
    runs-on: ubuntu-latest
    needs: [create-release]
    timeout-minutes: 5

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm bootstrap

      - name: Publish
        run: npx lerna publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
