name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release (example: 0.3.0)'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout the latest
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config user.email "bot@github.com"
          git config user.name "github-actions"

      - name: Bump version
        run: npm version ${{ github.event.inputs.version }} -m 'Version bump to %s'

      - name: Commit changes
        run: git push && git push --tags

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: true
          prerelease: false

  publish-gpr:
    runs-on: ubuntu-latest
    needs: [create-release]
    timeout-minutes: 2

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: blotoutio

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_REPO}}

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_TOKEN}}
