name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release (example: 0.3.0)'
        required: true

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config user.email "bot@github.com"
          git config user.name "github-actions"

      - name: Core
        run: cd packages/sdk-core && npm --no-git-tag-version version ${{ github.event.inputs.version }}

      - name: Personal
        run: cd packages/sdk-personal && npm --no-git-tag-version version ${{ github.event.inputs.version }}

      - name: Browser
        run: cd packages/sdk-browser && npm --no-git-tag-version version ${{ github.event.inputs.version }}

      - name: Commit changes
        run: git add . && git commit -m 'Version bump to ${{ github.event.inputs.version }}' && git push

  create-release:
    runs-on: ubuntu-latest
    needs: [version-bump]
    timeout-minutes: 1

    steps:
      - name: Checkout the latest
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config user.email "bot@github.com"
          git config user.name "github-actions"

      - name: Tag
        run: git tag -a ${{ github.event.inputs.version }} -m 'Version bump to ${{github.event.inputs.version}}'

      - name: Commit changes
        run: git push --tags

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: true
          prerelease: false

  publish-core:
    runs-on: ubuntu-latest
    needs: [create-release]
    timeout-minutes: 2
    defaults:
      run:
        working-directory: packages/sdk-core

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_REPO}}

      - name: Build
        run: npm run build

      - name: Publish package
        run: cd dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

  publish-personal:
    runs-on: ubuntu-latest
    needs: [publish-core]
    timeout-minutes: 2
    defaults:
      run:
        working-directory: packages/sdk-personal

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm i @blotoutio/sdk-core
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_REPO}}

      - name: Build
        run: npm run build

      - name: Publish package
        run: cd dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

  publish-browser:
    runs-on: ubuntu-latest
    needs: [publish-personal]
    timeout-minutes: 2
    defaults:
      run:
        working-directory: packages/sdk-browser

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm i @blotoutio/sdk-core @blotoutio/sdk-personal
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_REPO}}

      - name: Build
        run: npm run build

      - name: Publish package
        run: cd dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
