name: Tests Matrix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x]

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cache/Cypress
            packages/sdk-core/node_modules
            packages/sdk-personal/node_modules
          key: ${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('packages/sdk-core/package-lock.json') }}-${{ hashFiles('packages/sdk-personal/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Bootstrap lerna
        run: npm run bootstrap

      - name: Run tests
        run: npm run test
