name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            packages/sdk-browser/node_modules
            packages/sdk-core/node_modules
            packages/sdk-personal/node_modules
          key: ${{ hashFiles('packages/sdk-browser/package-lock.json') }}-${{ hashFiles('packages/sdk-core/package-lock.json') }}-${{ hashFiles('packages/sdk-personal/package-lock.json') }}

      - name: Bootstrap lerna
        run: npm run bootstrap

      - name: Run tests
        run: npm run test

      - name: Coverage sdk-core
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: packages/sdk-core/coverage/coverage-final.json
          flags: sdk-core

      - name: Coverage sdk-personal
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: packages/sdk-personal/coverage/coverage-final.json
          flags: sdk-personal
